# Generated by Django 2.1.1 on 2018-10-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='number_of_unique_words',
        ),
    ]
