# Generated by Django 2.1.1 on 2018-10-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_remove_notice_number_of_unique_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='numbers',
            field=models.IntegerField(default=0),
        ),
    ]
